### ISSUE TITLE
SCITE lineage

### ISSUE THREAD

**Issue by alanfoleynibrt** [single-cell-genetics/MQuad#15]
Hi

I notice in your paper (https://www.nature.com/articles/s41467-022-28845-0) you use SCITE to approximate lineage of cells.

Can I perhaps see the code you used (with the parameters) for running SCITE?

I understand it would look something like this:

##
../infSCITE \
-i MutationMatrix.csv \
-n 23 \
-m 10 \
-r 1 \
-l 700000 \
-fd 3.45e-3 \
-ad 1.46e-1 \
-s \
-e .2 \
-p 10000 \
-d -rec 13
##

Alan

**Comment by aaronkwc** [comment]
Hi Alan,

Sorry but I do not have the exact script saved, but I just used the command from the SCITE tutorial (https://github.com/cbg-ethz/SCITE)

`./scite -i genotype_matrix.csv -n 24 -m 5 -r 1 -l 900000 -fd 6.04e-5 -ad 0.21545 0.21545 -cc 1.299164e-05 -transpose`

Apologies again but hope this helps.

Aaron

**Comment by alanfoleynibrt** [comment]
That's great thanks for the reply Aaron.

I'm not 100% sure what each option is doing so I'll have to do some learning!

Alan
