### ISSUE TITLE
Could be used for whole genome scATAC data analysis?

### ISSUE THREAD

**Issue by liufuyan2016** [single-cell-genetics/MQuad#16]
Hi,
Could I use MQuad for the whole genome scATAC data analysis and not only for chrMt?
 I used the following command :
mquad -o Y_F1/ --minDP 5 --vcfData Y_F1/Y_F1_SNP/cellSNP.cells.vcf.gz
and the error is below:
  File "/jdfsbjcas1/ST_BJ/PUB/User/kangjingmin/Pipline/local/bin/mquad", line 8, in <module>
    sys.exit(main())
  File "/home/kangjingmin/.local/lib/python3.9/site-packages/mquad/mquad_CLI.py", line 132, in main
    df = mdphd.fit_deltaBIC(
  File "/home/kangjingmin/.local/lib/python3.9/site-packages/mquad/mquad_batch_mixbin.py", line 132, in fit_deltaBIC
    x, y = zip(*[(r, c) for r, c in zip(dp_row, dp_col) if r in valid_rows])
ValueError: not enough values to unpack (expected 2, got 0)

Could you help me!
Thank you!

**Comment by aaronkwc** [comment]
Hi @liufuyan2016 ,

Thanks for using MQuad. 

Firstly, MQuad is designed for single-cell data where it detects heterogeneity within a population of cells. The informative variants it detects represent variants that can discriminate clonal populations. One bulk whole genome scATAC-seq is not applicable in this case. Can you please be more specific your use case in case I misunderstood?

Secondly, MQuad's model is specifically designed for chrM where the heteroplasmy varies a lot from 0-100%, while in the diploid genome there are only 3 major genotypes - homo recessive, homo dominant, and heterozygous. There are plenty of other software that identifies clonaltype based on diploid variants, such as SCITE.

**Comment by liufuyan2016** [comment]
Thank you for reply!
I mean I have one single cell ATAC data and I want to call SNP for whole genome (nuclear genome + Mt genome). Could the software support?

**Comment by aaronkwc** [comment]
Sorry but MQuad was not designed to identify clonal variants in the nuclear genome. For this purpose you should consider other specialized software. However, if you specify cellSNP.cells.vcf.gz to only contain chrM variants, it should work. You can do this by either filtering the cellSNP output or by running cellSNP with the option `chrom=chrM`

**Comment by liufuyan2016** [comment]
Thank you quickly reply！In your published article, which tools used for calling the nuclear SNV in figure3 ？Thanks you again!

**Comment by aaronkwc** [comment]
The nuclear SNVs in figure 3 is obtained from another paper:

https://www.nature.com/articles/s41592-020-0766-3

The clonal structure is identified with Cardelino (see Fig. 3)
