### ISSUE TITLE
Question about output files.

### ISSUE THREAD

**Issue by KazukiYoshimura0403** [single-cell-genetics/MQuad#19]
Hi!
I would like to reflect the mitochondrial genetic mutation results obtained by MQuad in the Dimplot created in Seurat (like Fig. 5d in your article about MQuad).
So, I need to link AD/DP matrices and cell barcodes. 
Do the 1st, 2nd and 3rd columns of "passed_ad/dp.mtx" mean variants, cell barcodes and depth(ad/dp) respectively?
And the numbers of variants and cell barcodes accord with the order of "passed_variant_names.txt" and "cellSNP.samples.tsv"(which is in the input directory)?

**Comment by aaronkwc** [comment]
Hi,

You are correct that the AD/DP matrices and cell barcodes have to be linked up. The .mxt files are in Matrix Market format: as in the columns refer to the [row_index, column_index, value]. However, you do not have to manually process it as sparse matrix functions in R `readMM` and python `scipy.io.mmread()` should be able to read the matrices as is.

The `passed_ad.mtx` and `passed_dp.mtx` give you a AD or DP x cell matrix respectively. The barcode and variant order follow `cellSNP.samples.tsv` and `passed_variants_names.txt` as you pointed out.

**Comment by KazukiYoshimura0403** [comment]
Thank you for your comment! 
I was able to make AD and DP matrices and merge them to meta data of Seurat data.
