### ISSUE TITLE
bbmix error

### ISSUE THREAD

**Issue by nrohani** [single-cell-genetics/MQuad#21]
Hi, 
I'm trying to fit mquad on the output of cellsnp for 3' 10x single cell data. I got the following error:

16569 variants detected...

Variant names detected...

CPUs used: 20, batch size: 5 

Fitting in sparse mode...

Initializing fit(mode: deltaBIC) on 16569 variants...

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: divide by zero encountered in log

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: invalid value encountered in multiply

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:116: RuntimeWarning: divide by zero encountered in log

  np.log(1 - p_k) + np.log(pi_k)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:115: RuntimeWarning: invalid value encountered in multiply

  E_gammas[k] = y * np.log(p_k) + (n - y) * \

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: divide by zero encountered in log

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: invalid value encountered in multiply

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:116: RuntimeWarning: divide by zero encountered in log

  np.log(1 - p_k) + np.log(pi_k)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:115: RuntimeWarning: invalid value encountered in multiply

  E_gammas[k] = y * np.log(p_k) + (n - y) * \

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: divide by zero encountered in log

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: invalid value encountered in multiply

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:116: RuntimeWarning: divide by zero encountered in log

  np.log(1 - p_k) + np.log(pi_k)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:115: RuntimeWarning: invalid value encountered in multiply

  E_gammas[k] = y * np.log(p_k) + (n - y) * \

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: divide by zero encountered in log

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: invalid value encountered in multiply

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:116: RuntimeWarning: divide by zero encountered in log

  np.log(1 - p_k) + np.log(pi_k)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:115: RuntimeWarning: invalid value encountered in multiply

  E_gammas[k] = y * np.log(p_k) + (n - y) * \

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: divide by zero encountered in log

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: invalid value encountered in multiply

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:116: RuntimeWarning: divide by zero encountered in log

  np.log(1 - p_k) + np.log(pi_k)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:115: RuntimeWarning: invalid value encountered in multiply

  E_gammas[k] = y * np.log(p_k) + (n - y) * \

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: divide by zero encountered in log

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: invalid value encountered in multiply

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:116: RuntimeWarning: divide by zero encountered in log

  np.log(1 - p_k) + np.log(pi_k)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:115: RuntimeWarning: invalid value encountered in multiply

  E_gammas[k] = y * np.log(p_k) + (n - y) * \

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: divide by zero encountered in log

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: invalid value encountered in multiply

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:116: RuntimeWarning: divide by zero encountered in log

  np.log(1 - p_k) + np.log(pi_k)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:115: RuntimeWarning: invalid value encountered in multiply

  E_gammas[k] = y * np.log(p_k) + (n - y) * \

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: divide by zero encountered in log

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: invalid value encountered in multiply

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:116: RuntimeWarning: divide by zero encountered in log

  np.log(1 - p_k) + np.log(pi_k)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:115: RuntimeWarning: invalid value encountered in multiply

  E_gammas[k] = y * np.log(p_k) + (n - y) * \

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: divide by zero encountered in log

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: invalid value encountered in multiply

  + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:116: RuntimeWarning: divide by zero encountered in log

  np.log(1 - p_k) + np.log(pi_k)

/Users/nrohani/mquad_env1/lib/python3.10/site-packages/bbmix/models/binomial_mix_sparse.py:115: RuntimeWarning: invalid value encountered in multiply

  E_gammas[k] = y * np.log(p_k) + (n - y) * \

deltaBIC was calculated for 16569 variants and took:46.29 minutes

Out directory already exists, overwriting content inside...

deltaBIC cutoff =  666.1358156537099

Number of variants passing threshold: 91

Traceback (most recent call last):

  File "/Users/nrohani/mquad_env1/bin/mquad", line 8, in <module>

    sys.exit(main())

  File "/Users/nrohani/mquad_env1/lib/python3.10/site-packages/mquad/mquad_CLI.py", line 144, in main

    best_ad, best_dp = mdphd.selectInformativeVariants(min_cells = minCell, out_dir = out_dir, tenx_cutoff=cutoff)

  File "/Users/nrohani/mquad_env1/lib/python3.10/site-packages/mquad/mquad_batch_mixbin.py", line 231, in selectInformativeVariants

    renamed_vars.append((var.split('_')[1] + var.split('_')[2] + '>' + var.split('_')[3]))

IndexError: list index out of range

**Comment by aaronkwc** [comment]
Hi @nrohani ,

Haven't seen this error before so I need a little bit more context. Can you show me the command line used? and the first few lines of the input files will help a lot as well.
