### ISSUE TITLE
A little passed variants.

### ISSUE THREAD

**Issue by FionaMoon** [single-cell-genetics/MQuad#23]
Hi, 
I try to run MQuad on 10x scRNA-seq, parameters are set like this:
```
mquad --c $cellSNP_lite_output -o $wkdir/Pt_12_Dx_MQuad/mquad \
-p 5 --batchFit 1 --batchSize 5 --minDP 5
```
The passed_variant_names.txt contains only 3 variants.
I've tried to use a lower --minDP, but it doesn't help. 
What should I do to get more output variants?

Thank you in advance.

**Comment by aaronkwc** [comment]
Hi @FionaMoon 

Calling mitonchondrial variants on 10x data is not very consistent as the coverage is very uneven and shallow. Please refer to issue #22 for a more detailed explanation.

You can also use the 10X mode with `--tenx` to specify a deltaBIC cutoff yourself. This would require a bit more caution as you would be arbitarily setting a threshold.

**Comment by FionaMoon** [comment]
Thank you!
