### ISSUE TITLE
issue with mquad

### ISSUE THREAD

**Issue by sxf-ux** [single-cell-genetics/MQuad#26]
Hi. I am running mquad with 10X scRNA seq data using the following command:

`mquad -m cellSNP.tag.AD.mtx, cellSNP.tag.DP.mtx -o $output_dir --minDP 5`

and I received this in my log while running it:

**_Fitting in sparse mode...
Initializing fit(mode: deltaBIC) on 16569 variants...
mquad_env/lib/python3.9/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: divide by zero encountered in log + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)
mquad_env/lib/python3.9/site-packages/bbmix/models/binomial_mix_sparse.py:156: RuntimeWarning: invalid value encountered in multiply + y * np.log(p) + (n - y) * np.log(1 - p) + np.log(pi)
mquad_env/lib/python3.9/site-packages/bbmix/models/binomial_mix_sparse.py:116: RuntimeWarning: divide by zero encountered in lognp.log(1 - p_k) + np.log(pi_k)
mquad_env/lib/python3.9/site-packages/bbmix/models/binomial_mix_sparse.py:115: RuntimeWarning: invalid value encountered in multiply E_gammas[k] = y * np.log(p_k) + (n - y) * \_**

I used `--min DP5` as it is recommended for 10X data according to the manual. Do you happen to know why this issue is there or what this could mean? it appears that the package dependencies aren't correlating like they should but I don't fully understand this. 

Thank you in advance!

**Comment by aaronkwc** [comment]
Are the output files generated normally? This warning is normal as some positions inherently have very poor coverage and model fitting can be problematic with such sparsity, but MQuad should be able to ignore them and keep running for other positions.

Unless the output files have problems I think this warning can be safely ignored for the most part.

**Comment by sxf-ux** [comment]
Hi. The outputs I have were:

`BIC_params.csv` ` debug_unsorted_BIC_params.csv`  `deltaBIC_cdf.pdf`

should it also not include the passed_ad.mtx and passed_dp.mtx files too?

**Comment by sxf-ux** [comment]
I also wanted to add that when downloading the package using `pip install -U mquad` there is an error. 

ive included it in here to help with any debugging.

  Using cached mquad-0.1.7-py3-none-any.whl.metadata (5.6 kB)
Collecting numpy>=1.9.0 (from mquad)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ���������������������������������������� 61.0/61.0 kB 1.3 MB/s eta 0:00:00
Collecting scipy>=1.4.0 (from mquad)
  Downloading scipy-1.12.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ���������������������������������������� 60.4/60.4 kB 3.6 MB/s eta 0:00:00
Collecting matplotlib (from mquad)
  Downloading matplotlib-3.8.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting BBMix>=0.2.1 (from mquad)
  Using cached bbmix-0.2.2.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Collecting vireoSNP (from mquad)
  Using cached vireoSNP-0.5.8.tar.gz (1.7 MB)
  Preparing metadata (setup.py) ... done
Collecting kneed (from mquad)
  Using cached kneed-0.8.5-py3-none-any.whl.metadata (5.5 kB)
Collecting pandas (from mquad)
  Downloading pandas-2.2.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting seaborn (from mquad)
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting sklearn (from mquad)
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  � python setup.py egg_info did not run successfully.
  � exit code: 1
  ��> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

� Encountered error while generating package metadata.
��> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by aaronkwc** [comment]
Sorry for the late reply. The output files not being properly generated might be due to some of the plotting functions being deprecated in matplotlib, but there should be an error message at the end indicated so. Another problem might be due to lack of fit in too many positions due to insufficient depth. Can you also check if the BIC_params.csv has info at all?

For the installation issue, it is due to the sklearn namespace being deprecated and replaced fully by scikit-learn. This is taken care of in the latest commit and will be fixed in the next release.
