### ISSUE TITLE
mt variants only

### ISSUE THREAD

**Issue by bio-ruxandra-tesloianu** [single-cell-genetics/MQuad#3]
Hi!
disclaimer: I am not familiar with genotyping. 

 I was thinking about using MQuad on my scRNAseq data. The guide says I should use cellSNP/cellSNP-lite first. However, these would detect variants in the entire genome, not just mitochondrial ones. Should I subset the original cellranger bam file to only contain the mito reads?

**Comment by aaronkwc** [comment]
Hi,

Thanks for your question. Subseting the original bam file using samtools would be one possible way, another way to do it is to use the --chrom option iin cellsnp-lite (set --chrom=MT), then the output will only be MT variants. Hope that helps.

**Comment by bio-ruxandra-tesloianu** [comment]
hi, thanks a lot! Just saw in the documentation that it has this option.

I also assume I would be using mode 2, since I dont have an existing list of SNPs.

**Comment by aaronkwc** [comment]
For more information, please see the newly created .sh in the repos:

https://github.com/single-cell-genetics/MQuad/blob/main/example/preprocessing_cmd.sh

This quick tutorial (?) should describe how to use cellsnp correctly. Marking this as closed.
