### ISSUE TITLE
vireo use

### ISSUE THREAD

**Issue by bio-ruxandra-tesloianu** [single-cell-genetics/MQuad#4]
I was trying to combine my MQuad outputs with vireo. I was wondering which MQuad outputs are passed to which arguments of vireo. Thanks!

P.S. The tutorial here does not load for me:
https://github.com/single-cell-genetics/vireo/blob/master/examples/vireoSNP_clones.ipynb

**Comment by aaronkwc** [comment]
MQuad outputs a passed_ad.mtx and passed_dp.mtx for the AD and DP arguments in vireo. If you don't find these in the mquad output folder, the deltaBIC might be too low to get a good cutoff. Are you using 10x 3' scRNA-seq data with shallow depth? Also, can you share the top 20 rows in the BIC_params.csv ?

**Comment by bio-ruxandra-tesloianu** [comment]
hi!

To give a back of background, this is not a cancer cell line, but rather an in vitro differentiation experiment. I was hoping to see if I can get clones and then associate them with specific cell types to do lineage reconstruction (I imagine the overlap won't be perfect but it could still be an indicator of the lineage tree). Would that be suitable or is the method really just for cancer?

**Comment by aaronkwc** [comment]
I see. MQuad has better performance in cancer but you can still try on other datasets. Personally I did not have much luck in embryonic datasets as they have too little time for mutations to occur. 

I suggest you use cellsnp with no filters ie. --minMAF 0 --minCOUNT 0 (see the example shell file in this repos) to pileup all positions first, this might increase your yield. Also a --minDP 5 or lower in MQuad might also help the fitting. If MQuad still produces a lot of fitting errors, then your dataset might not have that many mutations to be detected unfortunately.

**Comment by Cacti-Jiang** [comment]
Hi @aaronkwc,

I noticed that the outputs of MQuad did not refer to cell ids. Any advice on matching the mt clones and cells with vireo?

**Comment by aaronkwc** [comment]
Hi @Cacti-Jiang,

MQuad does not specifically assign cells to clones, vireo does, so there are no explicit cell ids in the output of MQuad.

However, if you are referring to matching clones assigned by vireoSNP to some other list of ids (ie. 10x barcode), you can access the clone ids in python by `np.argmax(model.ID_prob, axis=1)` , where model is the fitted model object when you use vireo. This returns a list of clone ids, length = n_cells. The order of the list is the same as the order of the AD/DP matrix input (which is the same as the order of the cell barcode list used in cellsnp). You can then do some simple table manipulation to match /concat them.

Did I understand your question correctly?

**Comment by Cacti-Jiang** [comment]
Thanks for the speedy responses! It works well~
