### ISSUE TITLE
ValueError: cannot reshape array of size 0 into shape (0,newaxis)

### ISSUE THREAD

**Issue by pcallen225** [single-cell-genetics/MQuad#5]
After running cellSNP on my 10X scRNA bam with parameters -p 22 --minMAF 0.1 --minCOUNT 100 --chrom chrMT I get the assumed correct output files [Attached] 
![image](https://user-images.githubusercontent.com/47501726/114890285-7ebce880-9dd0-11eb-82ae-448cae816c3d.png)

but when I run MQuad on the cellSNP output using parameters -p 20 --minDP 5 I get ValueError: cannot reshape array of size 0 into shape (0,newaxis). I've run this on 2 separate datasets and receive the same error. Could this be a python version issue? I'm on Python v.3.9.2.

**Comment by aaronkwc** [comment]
Hi @pcallen225 ,

As you can see, the output files size are extremely small (only a few Kb for example). If you cat the files, I suspect they are only a few variants, or maybe even empty.

This can happen by 2 reasons:
1. The UMI option in cellSNP was not set correctly. Maybe try adding the `--UMItag Auto` option.
2. Variants occurrence is too low and did not reach the filter threshold. Maybe use no filters on MAF anf minCOUNT `--minMAF 0 --minCOUNT 0` and see if the output file size are more reasonable?

As MQuad depends on the contrast between background noise and informative variants, if the input variants number is too little, errors might be returned. Hope this helps. You can also take a look at the shell file in the example folder for more specific options in cellsnp-lite command line.

**Comment by pcallen225** [comment]
Hey Aaron,

Thank you for the quick response! I altered the cellSNP parameters and number of variants went up to ~16k so I then used this as input for MQuad. This led to the same outcome. Could it be a python version issue?

My Version Packages are as follows:

• mquad 0.1.4
• cellsnp 0.3.2
• python 3.9.2


I tried looking at the bioarxiv for python version but was unable to find it.

Peter

**Comment by aaronkwc** [comment]
Hi Peter,

MQuad was written in python 3.8.3, but I tried the example file on python 3.9.2 conda environment and there doesn't seem to be a problem. Can you quickly run MQuad on the example file in the repos? 

Another possible cause might be the scRNA-seq has too low depth for any informative mtDNA variants to be detected. Are there any output files? ie. BIC_params.csv can tell if the deltaBIC is too low.

Aaron

**Comment by pcallen225** [comment]
Aaron,

After running on the example vcf file, it output what I was expecting. I compared the deltaBIC between the 2 data and found that the deltaBIC for my data is incredibly low compared to the Lareau vcf data. I may see if there are other public scRNA data that I can experiment with and use this tool. Thanks again for your help!

Peter
